### ISSUE TITLE
bug: invalid_client; client authentication failed

### ISSUE THREAD

**Issue by v0rs4** [logto-io/go#74]
### Describe the bug

I've come across this issue 

```
unexpected status code: 401, response body: {"error":"invalid_client","error_description":"client authentication failed"}
```

### Expected behavior

N/A

### How to reproduce?

- Create `Traditional Web` application
- Run [sample app](https://github.com/logto-io/go/tree/master/gin-sample) against it

### Context

N/A

### Possible Fix
Apparently there's [something wrong on this line](https://github.com/logto-io/go/blob/master/core/fetch_token.go#L31)

So, 

I replaced 

```go
response, requestErr := client.PostForm(options.TokenEndpoint, values)
```

with

```go
req, _ := http.NewRequest(http.MethodPost, options.TokenEndpoint, strings.NewReader(values.Encode()))

req.Header.Add("Authorization", "Basic <<<BASE64_ENCODED(CLIENT_ID:CLIENT_SECRET)>>>")
req.Header.Add("Content-Type", "application/x-www-form-urlencoded")

response, requestErr := client.Do(req)
```

**and it works now**

I don't have deep knowledge in `go` but it seems that  `logtoClient.httpClient` looses basic auth header somehow

---

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 1.3.1 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

**Comment by waltcow** [comment]
meet the same issue here

**Comment by xiaoyijun** [comment]
Fixed https://github.com/logto-io/go/pull/75

**Comment by xiaoyijun** [comment]
The new version was released. @v0rs4 @waltcow 
https://github.com/logto-io/go/releases/tag/v1.0.3
